#!/bin/sh
# Writes the git commit and build date into App/BuildStamp.xcconfig so the
# app can show which build is running (Home header and Settings). Run before
# `xcodegen generate`; local builds keep the committed "local" stamp.
set -e
cd "$(dirname "$0")/.."
COMMIT="$(git rev-parse --short=7 HEAD 2>/dev/null || echo unknown)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
DATE="$(date -u +%Y-%m-%dT%H:%MZ)"
cat > App/BuildStamp.xcconfig <<STAMP
// Generated by Scripts/build-stamp.sh — do not edit by hand.
PS_BUILD_COMMIT = $COMMIT
PS_BUILD_BRANCH = $BRANCH
PS_BUILD_DATE = $DATE
STAMP
echo "build stamp: $COMMIT ($BRANCH) $DATE"
